-- CRIACAO DE USUARIOS/ROLES, DATABASE, TABLESPACE

CREATE ROLE pg_users NOSUPERUSER NOINHERIT NOCREATEDB NOCREATEROLE;
CREATE ROLE pg_aplic NOSUPERUSER NOINHERIT NOCREATEDB NOCREATEROLE;

CREATE ROLE gsan_admin LOGIN PASSWORD 'gsan_admin' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE ROLE gsan_batch LOGIN PASSWORD 'gsan_batch' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE ROLE gsan_dba   LOGIN PASSWORD 'gsan_dba' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE ROLE gsan_olap  LOGIN PASSWORD 'gsan_olap'   NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE ROLE gsan_online LOGIN PASSWORD 'gsan_online' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

-- ATRIBUICAO DE PRIVILEGIOS

GRANT pg_aplic TO gsan_batch;
GRANT pg_aplic TO gsan_olap;
GRANT pg_aplic TO gsan_online;

GRANT pg_users TO gsan_admin;
GRANT pg_users TO gsan_batch;
GRANT pg_users TO gsan_dba;
GRANT pg_users TO gsan_online;
